### ISSUE TITLE
ReferenceError: key is not defined

### ISSUE THREAD

**Issue by isokasapupuja** [ravi0lii/node-sharex-server#11]
```
[SUCCESS] Now listening on port 14597
[AUTH] Authentication with key hyZ... succeeded
[INFO] Uploading file Test.png to uploads/cGVwojXf.png (hyZ...)
[INFO] Uploaded file Test.png to uploads/cGVwojXf.png (hyZ...)
/somepath/sharex/node-sharex-server/app.js:113
                    response.uploaded(res, config.staticFileServerUrl + payload.fileName, config.serverUrl + '/delete?filename=' + payload.fileName + '&key=' + key);
                                                                                                                                                                ^

ReferenceError: key is not defined
    at /somepath/sharex/node-sharex-server/app.js:113:161
    at /somepath/sharex/node-sharex-server/node_modules/express-fileupload/lib/utilities.js:56:57
    at WriteStream.<anonymous> (/somepath/sharex/node-sharex-server/node_modules/express-fileupload/lib/utilities.js:181:29)
    at WriteStream.emit (events.js:400:28)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

app exits after error
running on http

**Comment by isokasapupuja** [comment]
my bad, fixed in https://github.com/ravi0lii/node-sharex-server/pull/10
